package com.example.activiteitenzoeker

object ActivityInformation {
        fun getInformation(): ArrayList<ActivityInformationDataClass>{
            val informationList = ArrayList<ActivityInformationDataClass>()
            val activity1 = ActivityInformationDataClass("Schaatsen",R.drawable.ic_schaatsen, "Op een kunstijsbaan kun je de hele winter schaatsen. Als je zelf geen schaatsen hebt, kun je ze huren bij de ijsbaan. Je kunt ook Curling spelen of ijshockey. Als je vaker wilt schaatsen en je schaatstechniek wil verbeteren, kun je zelfs wekelijks les nemen!")
            informationList.add(activity1)
            val activity2 = ActivityInformationDataClass("Bioscoop", R.drawable.ic_bioscoop,"Een bioscoop is de perfecte plek om samen iets te beleven. Met een zeer groot projectiescherm en superieure geluidskwaliteit komen de special effects het best tot hun recht. De sfeer maakt het kijken naar een film ook bijzonder: als iedereen om je heen in lachen uitbarst, gaan jij en je vrienden/vriendinnen ook lachen.")
            informationList.add(activity2)
            val activity3 = ActivityInformationDataClass("Film thuis kijken", R.drawable.ic_film_thuis_kijken, "Bij het kijken van een film thuis ben je heel vrij in je keuzes: je kan met je vrienden/vriendinnen een eigen sfeer maken, beginnen te kijken op een moment dat jullie dat willen en makkelijk naar een andere film switchen als de film je niet bevalt. Bovendien kost het veel minder dan naar de bioscoop gaan!")
            informationList.add(activity3)
            val activity4 = ActivityInformationDataClass( "Truth or Dare", R.drawable.ic_truth_or_dare, "Het spel Truth or Dare is een uitdagend spel, waarvoor je geen voorbereidingen of dure materialen nodig hebt. Met dit spel heb je de mogelijkheid om de andere spelers uit te dagen en natuurlijk om ze zichzelf voor gek te laten zetten. Daardoor leer je iedereen op een heel andere manier kennen.")
            informationList.add(activity4)
            val activity5 = ActivityInformationDataClass("Thirty Seconds",R.drawable.ic_thirty_seconds,"Bij het spel 30 Seconds draait het om snelheid en het zo exact mogelijk omschrijven van begrippen. Pak een kaart van de stapel en probeer binnen 30 seconden de vijf omschrijvingen zo goed mogelijk te omschrijven zonder namen te noemen en 'Klinkt als technieken' te gebruiken. Om de beurt wisselt het team van 'omschrijver'. Wie de meeste begrippen raadt wint!")
            informationList.add(activity5)
            val activity6 = ActivityInformationDataClass("Efteling", R.drawable.ic_efteling, "De Efteling biedt een unieke combinatie van rustig amusement en spannende attracties, zoals de Bobsleebaan, Python (achtbaan), Baron 1898 (duikachtbaan), Piraña (wildwaterbaan) en Joris en de Draak (houten race achtbaan). Al deze attracties geven een enorme adrenaline kick. Ongetwijfeld zijn er nieuwe attracties die ook jij nog niet hebt beleefd sinds je laatste bezoek.")
            informationList.add(activity6)
            val activity7 = ActivityInformationDataClass( "Dierentuin", R.drawable.ic_dierentuin, "Een dierentuin biedt vermaak en ontspanning, kan leerzaam zijn en helpen bij het behoud van diersoorten. Iedere dierentuin heeft zijn eigen specialiteiten. De voedermomenten van de dieren zijn altijd bijzonder mee te maken. Verder trekken pasgeboren dieren, zoals een olifantje, altijd veel aandacht. ")
            informationList.add(activity7)
            val activity8= ActivityInformationDataClass("Walibi", R.drawable.ic_walibi, "Walibi is het spectaculairste attractiepark van Nederland. Voor de echte sensatiezoekers heeft het park elf attracties waarin je te maken krijgt met angstaanjagende hoogtes en heftige drops! Het park staat in Biddinghuizen in Flevoland. Ze hebben zelfs evenementen bij Hallowee zoals de Halloween Fright Nights en Halloween Spooky Days. ")
            informationList.add(activity8)
            val activity9=ActivityInformationDataClass("Overdekt zwembad", R.drawable.ic_overdekt_zwembad, "Let bij het kiezen van een zwembad op de extra faciliteiten, die een zwembad biedt, zoals glijbanen, bubbelbaden, stroomversnellingen, waterspuiters, een golfslagbad, een aqua cinema sauna’s en een restaurant. ")
            informationList.add(activity9)
            val activity10=ActivityInformationDataClass("Buiten zwembad",  R.drawable.ic_buiten_zwembad, "Heel geschikt voor een mooie zomerdag. Een groot voordeel van een zwembad ten opzichte van zwemmen in natuurwater is, dat het zwemwater verwarmd is, vaak een glijbaan heeft en mogelijkheden heeft om snacks te kopen. ")
            informationList.add(activity10)
            val activity11=ActivityInformationDataClass("Strand",  R.drawable.ic_strand, "Volop keuzemogelijkheden: zonnen op het strand, zwemmen in zee, chillen bij een beachclub, wandelen/fietsen langs het strand/in de duinen, garnalen vissen, suppen, vliegeren, voetballen, beachvolleybal, etc. ")
            informationList.add(activity11)
            val activity12=ActivityInformationDataClass("Beachvolleybal",  R.drawable.ic_beachvolleybal, "Beachvolleybal is een echte teamsport. Samenwerken, springen, duiken en dit alles met je voeten in het zand en met uitzicht op zee! Het is een ideale activiteit voor zowel kleine als grote groepen en kan zo fanatiek gespeeld worden als de groep zelf wil. ")
            informationList.add(activity12)
            val activity13=ActivityInformationDataClass("Surfen",  R.drawable.ic_surfen, "Surfen is een uitdagende watersport, waarbij je gebruik maakt van de kracht van de golven en de branding van de zee. Als je het voor de eerste keer doet, is het verstandig les te nemen. Er zijn verschillende surfboards die je kunt huren inclusief een wetsuit als bescherming tegen het koude zeewater. ")
            informationList.add(activity13)
            val activity14=ActivityInformationDataClass("Suppen",  R.drawable.ic_suppen, "Suppen is een mooie manier om de stad te zien. Heerlijk rustig over het water cruisen en toch actief bezig zijn. In principe mag je overal suppen waar water is. Je kunt een supboard (en eventueel wetsuit voor als het water nog koud is) op heel veel plaatsen huren. Vaak kun je ook les krijgen.")
            informationList.add(activity14)
            val activity15=ActivityInformationDataClass("Kanoën",  R.drawable.ic_kanoen, "Met een kano kun je een mooie tocht door een stad of een natuurgebied maken. In een Canadese kano kun je met meerdere personen zitten. Als je er een huurt, krijg je vaak een waterdichte ton en een waterkaart mee. Je roeit dan met een peddel. In een kajak vaar je met een dubbelbladspeddel.")
            informationList.add(activity15)
            val activity16=ActivityInformationDataClass("Vliegeren",  R.drawable.ic_vliegeren, "Vliegers zijn er in alle soorten, maten en prijsklassen: van de bekende éénlijnvliegers van €5,50 tot matrasvliegers van ruim €1.000. Stuntvliegers zijn er al vanaf €15 en die zijn geschikt voor een hele brede doelgroep. Vliegeren kun je heel snel leren. Het is verrassend om erachter te komen hoe je moet sturen en hoe krachtig de vliegers zijn. ")
            informationList.add(activity16)
            val activity17=ActivityInformationDataClass("Windsurfen",  R.drawable.ic_windsurfen,"Windsurfen is heel populair op de binnenmeren, maar ook op zee leeft een echte windsurfcultuur. Het is een laagdrempelige sport: je hebt de basis snel onder de knie. Om echt goed te worden, moet je nog flink wat tijd doorbrengen op het water. Je kunt een surfplank (en een wetsuit tegen de koud) op heel veel plaatsen huren. Vaak kun je ook les krijgen.")
            informationList.add(activity17)
            val activity18=ActivityInformationDataClass("Boek lezen",  R.drawable.ic_boek_lezen,"Lezen is een ideale activiteit als je iets wil doen zonder dat er andere personen bij betrokken zijn. Je kunt het op ieder moment van de dag doen, zo lang/kort als je wilt. Als je een goed boek leest, kun je zo meegevoerd worden door wat de personages uit het boek meemaken, dat je alles om je heen vergeet.")
            informationList.add(activity18)
            val activity19=ActivityInformationDataClass("Nieuwe taal leren",  R.drawable.ic_nieuwe_taal_leren, "Als je met een nieuwe taal begint, zul je verrast worden hoe snel je je woordenschat kunt uitbreiden. Er zijn veel apps te vinden die je helpen met het leren van een taal. Leuk als voorbereiding op een verre vakantie, of om buitenlandse mensen in je omgeving in hun eigen taal te kunnen aanspreken.")
            informationList.add(activity19)
            val activity20=ActivityInformationDataClass("Schilderen",  R.drawable.ic_schilderen, "Schilderen is een creatieve activiteit, waarmee je kunt improviseren en ook je gevoelens goed tot uitdrukking kan brengen. Schilderen geeft heel veel plezier en voldoening als er iets ontstaat op je papier of doek. Je kunt dit alleen doen, maar het is ook erg leuk om het met anderen te doen, omdat je elkaar dan feedback kunt geven.")
            informationList.add(activity20)
            val activity21=ActivityInformationDataClass("Tekenen",  R.drawable.ic_tekenen,"Tekenen is een creatieve activiteit, die je helpt te relaxen. Op YouTube staan heel veel teken-tutorials. Tekenen is een kwestie van op de juiste manier leren kijken en natuurlijk veel oefenen. Als je je vaardigheden hebt ontwikkeld, kun je op Instagram laten zien hoe goed je bent geworden.")
            informationList.add(activity21)
            val activity22=ActivityInformationDataClass("Kleien",  R.drawable.ic_kleien, "Het werken met klei is zeer afwisselend: het werkstuk dat je wil maken, de soort klei, handvormen of draaien. Als je creatie nog niet helemaal naar je zin is, kun je het makkelijk aanpassen. Je kunt je het afmaken door het te glazuren.")
            informationList.add(activity22)
            val activity23=ActivityInformationDataClass("Paasdoos maken",  R.drawable.ic_paasdoos_maken,"Je maakt een Paasdoos om iemand te verrassen bij het Paasontbijt. Gebruik je creativiteit om bijvoorbeeld een doos te knutselen in de klassieke vorm van een paashaas of juist iets heel anders. Je maakt de doos compleet met lekkere paasbroodjes, een geschilderd ei, flesje met versgeperste sinaasappelsap en een heerlijke croissant.")
            informationList.add(activity23)
            val activity24=ActivityInformationDataClass("Kerststukje maken",  R.drawable.ic_kerststukje_maken, "Versiering voor een kerststukje vind je in de tuin, in een tuincentrum of in een kringloopwinkel. Je gebruikt een stukje oase als basis. Je kunt al je creativiteit kwijt om er iets moois van te maken en je kan zelf iemand anders blij maken met het geven van een kerststukje.")
            informationList.add(activity24)
            val activity25=ActivityInformationDataClass("Terrarium maken",  R.drawable.ic_terrarium_maken,"Een terrarium is een afgesloten tuintje, dat zichzelf onderhoudt via een eigen ecosysteem. De belangrijkste dingen die je nodig hebt zijn een glazen pot met kurk, plantjes die houden van een hoge luchtvochtigheid, potgrond en wat actieve houtskool. Ook leuk om als cadeau te geven.")
            informationList.add(activity25)
            val activity26=ActivityInformationDataClass("Bob Ross tutorial volgen", R.drawable.ic_bob_ross_tutorial_volgen, "Bob Ross heeft een YouTube kanaal met ruim 400 filmpjes van 30 minuten over ‘The joy of painting’. Hierin legt hij uit hoe je landschappen kan schilderen. Volgens hem is het onmogelijk om fouten te maken.")
            informationList.add(activity26)
            val activity27=ActivityInformationDataClass("Muffins bakken",R.drawable.ic_muffins_bakken, "Een basisrecept vind je makkelijk op internet. Als je éénmaal door hebt hoe je een muffin bakt, kun je eindeloos variëren met meelsoorten en ingrediënten. Muffins zijn ook lekker als ontbijt, bij je lunch of als tussendoortje.")
            informationList.add(activity27)
            val activity28=ActivityInformationDataClass("Taart bakken",R.drawable.ic_taart_bakken, "Voordeel van een zelfgebakken taart is, dat die veel lekkerder is dan een taart uit de supermarkt of van een gewone bakker. Je kan zelf bepalen wat voor smaak je taart heeft en op internet zijn veel verschillende recepten te vinden die bij je passen.")
            informationList.add(activity28)
            val activity29=ActivityInformationDataClass("Koekjes decoreren",R.drawable.ic_koekjes_decoreren, "Koekjes decoreren is niet moeilijk, je moet het gewoon proberen en je zult dan zien dat het steeds gemakkelijker gaat. Het leukste is om de koekjes zelf ook te bakken. Je kunt de decoratie aanpassen aan de gelegenheid waarvoor je ze maakt: Voetbalwedstrijd, Koningsdag, etc.")
            informationList.add(activity29)
            val activity30=ActivityInformationDataClass("Moestuintje starten",R.drawable.ic_moestuintje_starten, "Als je net begint met moestuinieren, kun je het beste starten met groenten die makkelijk te telen zijn: sla, courgette, wortel, radijs, spinazie en snijbiet. Deze groenten hebben naast het water geven weinig verzorging nodig. Je oogst kan dus bijna nooit mislukken!")
            informationList.add(activity30)
            val activity31=ActivityInformationDataClass("Wadlopen",R.drawable.ic_wadlopen,"Wadlopen is een ervaring die simpelweg niet op je bucketlist mag ontbreken. Al wandelend over de bodem van de zee, ontdek je waarom de Waddenzee UNESCO Werelderfgoed is. Omdat je ook rekening moet houden met het weer en eb en vloed, moet je wadlopen plannen.")
            informationList.add(activity31)
            val activity32=ActivityInformationDataClass("Hints",R.drawable.ic_hints,"Hints is super eenvoudig en je kunt er al je creativiteit in kwijt. Je kunt het spelen met z’n tweeën, maar hoe meer er meedoen, hoe leuker het is. Je kunt gebruik maken van bestaande thema’s in een speldoos of zelf thema’s bedenken. Je kunt het competitief spelen, maar ook gewoon voor de gezelligheid.")
            informationList.add(activity32)
            val activity33=ActivityInformationDataClass("NEMO bezoeken",R.drawable.ic_nemo_bezoeken,"NEMO in Amsterdam is een interactief museum, waarin je kunt zien, horen en ervaren hoe wetenschappelijke fenomenen en technologie ons dagelijks leven beïnvloeden. Zoek een rustige dag op, zodat je niet te lang hoeft te wachten bij de activiteiten, proefjes in het laboratorium of workshops.")
            informationList.add(activity33)
            val activity34=ActivityInformationDataClass("Amsterdam light festival",R.drawable.ic_amsterdam_light_festival,"Amsterdam Light Festival is een lichtkunstfestival in de buitenlucht. In de winterperiode laten lichtkunstenaars bijzondere werkstukken zien in de openbare ruimte van de stad. Je kunt een route op en rond het water per boot, lopend of fietsend bekijken.")
            informationList.add(activity34)
            val activity35=ActivityInformationDataClass("Amsterdam Lookout",R.drawable.ic_amsterdam_lookout,"Amsterdam Lookout is een observatiedek op 100 m hoogte, van waaraf je een spectaculair uitzicht hebt op de binnenstad en haven van Amsterdam. Er staan interactieve verrekijkers en er is ook een schommel, waarmee je over de rand van het gebouw kan schommelen als je dat durft.")
            informationList.add(activity35)
            val activity36=ActivityInformationDataClass("Twister",R.drawable.ic_twister,"Het leuke van Twister is, dat de deelnemers op het laatst de meest acrobatische standen in moeten nemen om nog een vrije cirkel van de juiste kleur te bereiken. Hoewel het typisch een kinderspel is, kan het ook populair zijn bij studentenfeestjes.")
            informationList.add(activity36)
            val activity37=ActivityInformationDataClass("Bucket hat maken",R.drawable.ic_bucket_hat_maken,"Je ziet de bucket hat tegenwoordig in alle vormen en maten in het straatbeeld opduiken. Als je hem zelf maakt, kun je zelf de stof en kleur kiezen en kun je hem ook aanpassen aan je specifieke wensen, bijvoorbeeld voor een voetbalwedstrijd, Koningsdag, etc.")
            informationList.add(activity37)
            val activity38=ActivityInformationDataClass("Karaoke avond",R.drawable.ic_karaoke_avond,"Je kunt gebruik maken van een karaoke installatie. Als je die niet hebt, kun je je laptop gebruiken met een speaker. Op YouTube zijn er verschillende karaoke kanalen, waarop de leukste meezing tracks staan.")
            informationList.add(activity38)
            val activity39=ActivityInformationDataClass("IJsje halen",R.drawable.ic_ijsje_halen,"Heerlijk verkoelend én een gezellig uitje. Het lekkerste ijs haal je in een ijssalon. Zij hebben bijzondere smaken in een hoorntje, bakje of als je wil met spikkels. Er zijn zelfs ijssalons die broodjes met bolletjes ijs serveren als lunch.")
            informationList.add(activity39)
            val activity40=ActivityInformationDataClass("Voetballen",R.drawable.ic_voetballen, "Een potje voetbal kan altijd en overal. Het enige wat je nodig hebt is een bal en een stuk veld waarop je kan spelen. Met wat improvisatie deel je een veld in en maak je twee doelen en hoe meer mensen er mee doen, hoe leuker het wordt.")
            informationList.add(activity40)
            val activity41=ActivityInformationDataClass("High tea houden",R.drawable.ic_high_tea_houden,"Als je een high tea organiseert met meerdere mensen, kan iedereen iets lekkers meenemen, van zoete muffins tot pizzabroodjes en van scones tot sandwiches. Naast een grote pot thee kun je ook denken aan een zelfgemaakte smoothie of een lekker sapje.")
            informationList.add(activity41)
            val activity42=ActivityInformationDataClass("Escape room",R.drawable.ic_escape_room,"Een escape room zorgt voor de nodige spanning bij de deelnemers, helemaal omdat je van tevoren niet weet wat je moet verwachten. De meeste kamers moet je binnen een uur uitspelen. Heb je het niet gehaald binnen die 60 minuten, dan heb je het spel niet gewonnen.")
            informationList.add(activity42)
            val activity43=ActivityInformationDataClass("Online escape room",R.drawable.ic_online_escape_room,"Onder tijdsdruk samen online puzzels en raadsels oplossen en op het web speuren zorgt voor plezier en ontspanning. Bij een online escape game draait het om samenwerken als team en werken onder tijdsdruk.")
            informationList.add(activity43)
            val activity44=ActivityInformationDataClass("Pub quiz",R.drawable.ic_pub_quiz,"Het leuke van een Pub quiz is dat de vragen betrekking hebben op een groot aantal onderwerpen. Daarom gaat het niet zozeer om hoe slim je bent, maar om op het juiste moment het juiste antwoord op “weetjes” uit het geheugen naar boven te halen.")
            informationList.add(activity44)
            val activity45=ActivityInformationDataClass("Snowplanet",R.drawable.ic_snowplanet,"Op een indoor skipiste kun je op een eenvoudige manier genieten van het wintersportgevoel. En als je nog niet kunt skiën, is dit een mooie plek om het te gaan leren. Dan zul je bij je échte wintersport extra kunnen genieten.")
            informationList.add(activity45)
            val activity46=ActivityInformationDataClass("Dagje met boer meelopen",R.drawable.ic_dagje_met_boer_meelopen, "Ontdek het boerderij leven door te overnachten op een boerderij en mee te helpen met allerlei boerderijklusjes, zoals leren hoe je een koe moet melken, je eigen kaasje te maken, lammetjes de fles geven of zien hoe ijs gemaakt wordt van de melk van de eigen koeien.")
            informationList.add(activity46)
            val activity47=ActivityInformationDataClass("Pizza bakken",R.drawable.ic_pizza_bakken,"Je kunt ervoor kiezen om zelf pizzadeeg te maken, of om kant-en-klare pizzabodems te gebruiken. Je kunt zelf bepalen wat je voor pizza je wil maken en wat je erop doet: vlees, vis of zelfs vegetarisch.")
            informationList.add(activity47)
            val activity48=ActivityInformationDataClass("Sushi maken",R.drawable.ic_sushi_maken, "Sushi eten kan hartstikke lekker zijn, maar ook aan de prijzige kant. De oplossing: maak het zelf! Zelf sushi maken is écht niet moeilijk en een leuke activiteit. Wist je dat je sushi niet als hoofdgerecht gegeten wordt, maar met veel groente en andere gerechten erbij.")
            informationList.add(activity48)
            val activity49=ActivityInformationDataClass("Barbecueën",R.drawable.ic_barbecueen, "Barbecueën geeft een gevoel van vakantie, van vrijheid. Het is leuk om niet alleen de voorgevormde hamburgers te maken, maar te werken met verschillende soorten vlees, vis, groenten, maiskolven, aardappels en andere dingen.")
            informationList.add(activity49)
            val activity50=ActivityInformationDataClass("Touwtjespringen",R.drawable.ic_touwtjespringen, "Touwtjespringen is een hele effectieve krachttraining waarmee je je hele lichaam traint. Naast je fysieke conditie train je met touwtjespringen ook je snelheid en springvermogen, je gevoel voor ritme en coördinatie.")
            informationList.add(activity50)
            val activity51=ActivityInformationDataClass("Strandwandeling",R.drawable.ic_strandwandeling, "Een strandwandeling is een gezonde vorm van ontspanning en biedt veel afwisseling: mooie zonondergang, kite surfers bij harde wind, heerlijk met je voeten door de zee lopen. Een strandwandeling wordt extra bijzonder als je ook een deel door de duinen kunt lopen.")
            informationList.add(activity51)
            val activity52=ActivityInformationDataClass("Spa moment",R.drawable.ic_spa_moment,"Spa’s bestaan uit verschillende soorten baden, zwembaden, sauna’s, behandelingen en nog veel meer. Een Spa zorgt voor verzorging en ontspanning van je lichaam en je geest. Je vindt ze door het hele land en dus ook bij jou in de buurt.")
            informationList.add(activity52)
            val activity53=ActivityInformationDataClass("Sauna gaan",R.drawable.ic_sauna_gaan, "De sauna is een badhuis, waar je hete luchtbaden, stoombaden en koudwaterbaden kan nemen. Een sauna geeft door de warmte een ontspannend gevoel en kan gezellig zijn om samen te doen. Vaak kun je er ook nog iets eten en drinken.")
            informationList.add(activity53)
            val activity54=ActivityInformationDataClass("Schaken",R.drawable.ic_schaken, "Schaken is een strategisch spel, waarmee je een paar zetten vooruit moet denken. Daarmee train je bij deze denksport jouw hersenen, waardoor ze in topconditie blijven. Sinds het succes van de serie ‘The Queen’s Gambit’ op Nexflix is schaken sterk in populariteit toegenomen.")
            informationList.add(activity54)
            val activity55=ActivityInformationDataClass("Among us",R.drawable.ic_among_us, "In Among Us is het de bedoeling om met je groep in een ruimteschip te overleven, terwijl een andere groep probeert iedereen uit te moorden. Op vaste momenten mag iedereen mee praten en de anderen overtuigen om mensen weg te stemmen.")
            informationList.add(activity55)
            val activity56=ActivityInformationDataClass("Survivallen",R.drawable.ic_survivallen, "Je hebt twee types survival: midden in de natuur proberen te overleven met zo min mogelijk middelen, of een survivalrun die is opgezet als een urban trail / mud race. Aan jouw de keus!")
            informationList.add(activity56)
            val activity57=ActivityInformationDataClass("Bonbons maken",R.drawable.ic_bonbons_maken, "Bonbons uit de winkel zijn lekker, maar vaak prijzig. Als je ze zelf maakt, heb je siliconenvormpjes nodig. Je smelt chocolade en voegt er vullingen aan toe. Neem je iets wat je zelf lekker vindt of een vulling die wat makkelijker is om te maken of gebruiken.")
            informationList.add(activity57)
            val activity58=ActivityInformationDataClass("Vogelhuisje maken",R.drawable.ic_vogelhuisje_maken, "Met een nestkast lok je vogels naar je tuin. Let er op dat de maat van het vlieggat bepalend is, wat voor soort vogel in het hokje zal komen. Op de site van de vogelbescherming, zie je hoe je zelf een vogelhuisje kunt maken.")
            informationList.add(activity58)
            val activity59=ActivityInformationDataClass("Flashmob doen",R.drawable.ic_flashmob_doen, "Een flashmob is een plotselinge samenkomst van een groep mensen, die iets aparts doen en vervolgens weer even snel uit elkaar vallen. Een flashmob kan een alternatief zijn voor een examenstunt, als je die in verband met Covid-19 niet op school mag doen.")
            informationList.add(activity59)
            val activity60=ActivityInformationDataClass("Lasergamen",R.drawable.ic_lasergamen, "Lasergamen is net als paintballen en trefballen een spel waarbij je een ander probeert te raken en probeert zelf niet geraakt te worden. Het team dat de meesten keren raakt en het minst geraakt wordt, wint de game. Het grote voordeel van lasergamen is dat het geen pijn doet.")
            informationList.add(activity60)
            val activity61=ActivityInformationDataClass("Paintballen",R.drawable.ic_paintballen,"Paintball is een super spannende teamsport. Het doel van het spel is het vijandige team uitschakelen of één van de doelen van het spel te bereiken voordat de tegenstander dat doet. Paintballs worden met hoge druk uit paintball wapens geschoten.")
            informationList.add(activity61)
            val activity62=ActivityInformationDataClass("Klimmuur",R.drawable.ic_klimmuur,"Ben je sportief en ook een beetje avontuurlijk? Dan is klimmen iets voor jou. Je traint niet alleen je armen, maar ook je core, rug, schouders en benen. Ook je uithoudingsvermogen wordt flink op de proef gesteld en je zelfvertrouwen gaat een flinke boost tegemoet als je zo nu en dan de klimmuur op gaat.")
            informationList.add(activity62)
            val activity63=ActivityInformationDataClass("Trampoline park",R.drawable.ic_trampoline_park, "In een trampolinepark vind je trampolinevelden, dodgeball (soort trefbal), highperformance trampolines, walltrampolines, en evenwichtsbalken, air bag, foampits (sponsblokken), jumptower en een tumblinglane(lange trampoline voor trucs). Dus er is genoeg keuze!")
            informationList.add(activity63)
            val activity64=ActivityInformationDataClass("Frisbeeën",R.drawable.ic_frisbeeen, "Voor frisbeeën heb je een frisbee en een open plek/veld/strand nodig. Je speelt het met twee personen, maar meer kan ook. Je kunt een goedkope frisbee kopen in een speelgoedzaak. Er zijn ook professionelere frisbees in sportwinkels.")
            informationList.add(activity64)
            val activity65=ActivityInformationDataClass("City game",R.drawable.ic_city_game,"City game is een interactieve game, waarbij teams op verschillende onderdelen worden uitgedaagd. Een geweldige manier om een stad beter te leren kennen. Je kunt het in bijna alle grote steden van Nederland spelen.")
            informationList.add(activity65)
            val activity66=ActivityInformationDataClass("Boogschieten",R.drawable.ic_boogschieten,"Bij boogschieten staan al je zintuigen op scherp. Een boogschutter moet de juiste handelingen in de juiste volgorde uitvoeren tot hij voelt dat het goed zit en de pijl kan laten vertrekken. Het is een hele inspanning om je concentratie te bewaren en niet te trillen.")
            informationList.add(activity66)
            val activity67=ActivityInformationDataClass("Midgetgolf",R.drawable.ic_midgetgolf, "Als je nog geen golf ervaring hebt, is midgetgolf eenvoudiger en misschien zelfs wel leuker dan golf. Een midgetgolf parcours kent veel bijzondere hindernissen en obstakels in de vorm van loopings, bochten, tunnels, doolhoven en heuvels.")
            informationList.add(activity67)
            val activity68=ActivityInformationDataClass("Mountainbiken",R.drawable.ic_mountainbiken, "Mountainbiken is een mooie combinatie van kracht, uithoudingsvermogen, techniek, en coördinatie. Het is niet eenzijdig en dus perfect om op meerdere fronten fitter te worden. Bos, strand, weideland: niets is te gek voor een beetje off road bike.")
            informationList.add(activity68)
            val activity69=ActivityInformationDataClass("Geocaching",R.drawable.ic_geocaching,"Geocachen is een schatzoektocht op basis van gps-coördinaten, die je zoekt via een Geocaching app op je smartphone. De cache is gewoonlijk een kleine waterdichte doos, met de \"schat\" en een logboek, waarin de vinder zijn naam achter kan laten.")
            informationList.add(activity69)
            val activity70=ActivityInformationDataClass("GeoGuessr",R.drawable.ic_geoguessr, "GeoGuessr is een online spel waarbij je gedropt wordt ergens op de wereld via een Google Street View kaart. Je krijgt 5 plekken te zien waar jij probeert te raden waar deze plek is op de wereldkaart. Je mag 1 gok wagen en hoe dichter jouw gok bij de juiste plek is, hoe meer punten je krijgt.")
            informationList.add(activity70)
            val activity71=ActivityInformationDataClass("Indoor skydiven",R.drawable.ic_indoor_skydiven, "Als je eens een keer iets heel anders wil doen, dan is skydiven iets voor jou! Indoor skydiven doe je in een zogenoemde verticale windtunnel. In de windtunnel wordt de vrije val bij het parachutespringen nagebootst.")
            informationList.add(activity71)
            val activity72=ActivityInformationDataClass("Dropping",R.drawable.ic_dropping, "Bij een dropping wordt je geblinddoekt en ’s avonds/ ’s nachts in een klein groepje in de middle of nowhere wordt gedropt, waarna je op eigen houtje de weg terug moeten vinden en onderweg opdrachten moet vervullen. Zonder telefoon en zonder geld, maar met kaart en kompas.")
            informationList.add(activity72)
            val activity73=ActivityInformationDataClass("Ziplinen",R.drawable.ic_ziplinen,"Ziplinen is op een kabelbaan met grote snelheid afdalen aan een touw van een hoog punt naar een laag punt, terwijl je hangt aan een katrol. Er zijn zowel indoor als outdoor ziplines en je kan dit doen met zoveel mensen als je wilt!")
            informationList.add(activity73)
            val activity74=ActivityInformationDataClass("Luchtballonvaart",R.drawable.ic_luchtballonvaart, "Ballonvaren is een onvergetelijke gebeurtenis en kan bijna het hele jaar door gedaan worden. Een ochtend ballonvaart begint in de zomer al bij zonsopkomst. Het opstijgen en landen zijn het meest spectaculair.")
            informationList.add(activity74)
            return informationList

        }
    }