package com.example.activiteitenzoeker

object DatabaseActivities{
        fun getActivity(): ArrayList<Activity>{
                val activityList = ArrayList<Activity>()
                val schaatsen = Activity("altijd","altijd", "€", "actief","offline")
                activityList.add(schaatsen)
                val bioscoop = Activity("binnen","avond","€","passief","offline")
                activityList.add(bioscoop)
                val filmThuis =	Activity("binnen","altijd","gratis","passief","online")
                activityList.add(filmThuis)
                val truthOrDare	= Activity("binnen","altijd","gratis","actief","offline")
                activityList.add(truthOrDare)
                val thirtySeconds= Activity("binnen","altijd","gratis","actief","altijd")
                activityList.add(thirtySeconds)
                val efteling = Activity("buiten","altijd","€€€€","actief","offline")
                activityList.add(efteling)
                val dierentuin = Activity("buiten"	,"middag","€€€","actief", "offline")
                activityList.add(dierentuin)
                val walibi = Activity("buiten", "altijd", "€€€€", "actief", "offline")
                activityList.add(walibi)
                val overdektZwembad = Activity("binnen", "altijd","€", "actief", "offline")
                activityList.add(overdektZwembad)
                val buitenZwembad = Activity("buiten", "altijd", "€", "actief", "offline")
                activityList.add(buitenZwembad)
                val strand = Activity("buiten", "altijd", "gratis", "actief", "offline")
                activityList.add(strand)
                val beachvolleybal= Activity("buiten", "altijd", "gratis", "actief", "offline")
                activityList.add(beachvolleybal)
                val surfen = Activity("buiten", "middag", "€€€", "actief", "offline")
                activityList.add(surfen)
                val suppen = Activity("buiten",  "altijd", "€€€", "actief", "offline")
                activityList.add(suppen)
                val kanoen = Activity("buiten", "altijd", "€€€", 	"actief", "offline")
                activityList.add(kanoen)
                val vliegeren = Activity("buiten","altijd","gratis", "actief","offline")
                activityList.add(vliegeren)
                val windsurfen = Activity("buiten","middag","€€€€", "actief", "offline")
                activityList.add(windsurfen)
                val boekLezen = Activity("altijd","altijd","gratis","passief","altijd")
                activityList.add(boekLezen)
                val nieuweTaalLeren = Activity("binnen","altijd","gratis","actief","online")
                activityList.add(nieuweTaalLeren)
                val schilderen = Activity("altijd","altijd","€€€€","actief","offline")
                activityList.add(schilderen)
                val tekenen = Activity("altijd","altijd","gratis","actief","offline")
                activityList.add(tekenen)
                val kleien = Activity("binnen","altijd","€","actief","offline")
                activityList.add(kleien)
                val paasdoosMaken = Activity("binnen","altijd","€","actief","offline")
                activityList.add(paasdoosMaken)
                val kerststukjeMaken = Activity("binnen","altijd","€€","actief","offline")
                activityList.add(kerststukjeMaken)
                val terrariumMaken = Activity("binnen","altijd","€€","actief","offline")
                activityList.add(terrariumMaken)
                val bobRossTutorialVolgen = Activity("binnen","altijd","gratis","actief","online")
                activityList.add(bobRossTutorialVolgen)
                val muffinsBakken = Activity("binnen","altijd","€","actief","offline")
                activityList.add(muffinsBakken)
                val taartBakken = Activity("binnen","altijd","€","actief","offline")
                activityList.add(taartBakken)
                val koekjesDecoreren = Activity("binnen","altijd","€","actief","offline")
                activityList.add(koekjesDecoreren)
                val moestuintjeStarten = Activity("buiten","altijd","€","actief","offline")
                activityList.add(moestuintjeStarten)
                val wadlopen = Activity("buiten","altijd","€€€","actief","offline")
                activityList.add(wadlopen)
                val hints = Activity("binnen","altijd","gratis","actief","offline")
                activityList.add(hints)
                val nemoBezoeken = Activity("binnen","middag","€€€","actief","offline")
                activityList.add(nemoBezoeken)
                val amsterdamLightFestival = Activity("buiten","avond","gratis","actief","offline")
                activityList.add(amsterdamLightFestival)
                val amsterdamLookout = Activity("binnen","avond","gratis","actief","offline")
                activityList.add(amsterdamLookout)
                val twister = Activity("binnen","altijd","gratis","actief","offline")
                activityList.add(twister)
                val bucketHatMaken= Activity("binnen","altijd","gratis","actief","offline")
                activityList.add(bucketHatMaken)
                val karaokeAvond= Activity("binnen","avond","gratis","actief","offline")
                activityList.add(karaokeAvond)
                val ijsjeHalen = Activity("buiten","altijd","€","actief","offline")
                activityList.add(ijsjeHalen)
                val voetballen= Activity("buiten","altijd","gratis","actief","offline")
                activityList.add(voetballen)
                val highTeaHouden= Activity("binnen","middag","€","passief","offline")
                activityList.add(highTeaHouden)
                val escapeRoom = Activity("binnen","altijd","€€","actief","offline")
                activityList.add(escapeRoom)
                val onlineEscapeRoom = Activity("binnen","altijd","€","actief","online")
                activityList.add(onlineEscapeRoom)
                val pubQuiz = Activity("binnen","avond","gratis","actief","altijd")
                activityList.add(pubQuiz)
                val snowplanet = Activity("binnen","altijd","€€€€","actief","offline")
                activityList.add(snowplanet)
                val dagjeMetBoerMeelopen = Activity("buiten","altijd","€€€","actief","offline")
                activityList.add(dagjeMetBoerMeelopen)
                val pizzaBakken = Activity("binnen","avond","€","actief","offline")
                activityList.add(pizzaBakken)
                val sushiMaken = Activity("binnen","avond","€€","actief","offline")
                activityList.add(sushiMaken)
                val barbecueen = Activity("buiten","avond","€€","passief","offline")
                activityList.add(barbecueen)
                val touwtjeSpringen = Activity("buiten","altijd","gratis","actief","offline")
                activityList.add(touwtjeSpringen)
                val strandwandeling = Activity("buiten","altijd","gratis","actief","offline")
                activityList.add(strandwandeling)
                val spaMoment = Activity("binnen","altijd","€€€€","passief","offline")
                activityList.add(spaMoment)
                val saunaGaan = Activity("binnen","altijd","€€€","passief","offline")
                activityList.add(saunaGaan)
                val schaken = Activity("binnen","altijd","gratis","actief","altijd")
                activityList.add(schaken)
                val amongUs = Activity("binnen","altijd","gratis","actief","online")
                activityList.add(amongUs)
                val survivallen = Activity("buiten","altijd","€€€€","actief","offline")
                activityList.add(survivallen)
                val bonbonsMaken = Activity("binnen","altijd","€€€€","actief","offline")
                activityList.add(bonbonsMaken)
                val vogelhuisjeMaken = Activity("binnen","altijd","€€","actief","offline")
                activityList.add(vogelhuisjeMaken)
                val flashmobDoen = Activity("buiten","altijd","gratis","actief","offline")
                activityList.add(flashmobDoen)
                val lasergamen = Activity("altijd","middag","€€€","actief","offline")
                activityList.add(lasergamen)
                val paintballen = Activity("altijd","middag","€€€","actief","offline")
                activityList.add(paintballen)
                val klimmuur = Activity("binnen","altijd","€€€","actief","offline")
                activityList.add(klimmuur)
                val trampolinePark = Activity("altijd","altijd","€€","actief","offline")
                activityList.add(trampolinePark)
                val frisbeeen = Activity("buiten","altijd","gratis","actief","offline")
                activityList.add(frisbeeen)
                val cityGame = Activity("buiten","middag","€€€","actief","offline")
                activityList.add(cityGame)
                val boogschieten = Activity("buiten","middag","€€","actief","offline")
                activityList.add(boogschieten)
                val midgetgolf = Activity("buiten","altijd","€","actief","offline")
                activityList.add(midgetgolf)
                val mountainbiken = Activity("buiten","middag","€€€","actief","offline")
                activityList.add(mountainbiken)
                val geocaching = Activity("buiten","altijd","gratis","actief","altijd")
                activityList.add(geocaching)
                val geoGuessr = Activity("binnen","altijd","gratis","actief","online")
                activityList.add(geoGuessr)
                val indoorSkydiven = Activity("binnen","altijd","€€€€","actief","offline")
                activityList.add(indoorSkydiven)
                val dropping = Activity("buiten","avond","€€","actief","offline")
                activityList.add(dropping)
                val ziplinen = Activity("buiten","altijd","€€€€","actief","offline")
                activityList.add(ziplinen)
                val luchtballonvaart = Activity("buiten","altijd","€€€€","passief","offline")
                activityList.add(luchtballonvaart)
                return activityList
        }
}